// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	Message      string `json:"message"`
	UserName     string `json:"userName"`
	RoleName     string `json:"roleName"`
	DeptName     string `json:"deptName"`
	AccessToken  string `json:"token"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
	UserName string `json:"userName"`
}

type UserInfoResp struct {
	Name           string `json:"name"`             // 用户名
	NickName       string `json:"nick_name"`        // 昵称
	Avatar         string `json:"avatar"`           // 头像
	Password       string `json:"password"`         // 密码
	Email          string `json:"email"`            // 邮箱
	Mobile         string `json:"mobile"`           // 手机号
	Status         int64  `json:"status"`           // 状态  0：禁用   1：正常
	DeptId         int64  `json:"dept_id"`          // 部门ID
	CreateBy       string `json:"create_by"`        // 创建人
	CreateTime     int64  `json:"create_time"`      // 创建时间
	LastUpdateBy   string `json:"last_update_by"`   // 更新人
	LastUpdateTime int64  `json:"last_update_time"` // 更新时间
	DelFlag        int64  `json:"del_flag"`         // 是否删除  -1：已删除  0：正常
	RoleId         int64  `json:"role_id"`          // 岗位Id
	Sex            int64  `json:"sex"`              // 0男,1女
	Age            int64  `json:"age"`              // 默认0
}

type AddUserReq struct {
	Email          string `json:"email"`
	Mobile         string `json:"mobile,optional"`
	Name           string `json:"name"`
	NickName       string `json:"nickName,optional"`
	DeptId         int64  `json:"deptId"`
	RoleId         int64  `json:"roleId"`
	Avatar         string `json:"avatar,optional"`
	Password       string `json:"password"`
	LastUpdateBy   string `json:"lastUpdateBy"`
	LastUpdateTime int64  `json:"lastUpdateTime"`
}

type AddUserResp struct {
	Message string `json:"message"`
}

type ListUserReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type ListUserData struct {
	Id             int64  `json:"id"`               // 编号
	Name           string `json:"name"`             // 用户名
	NickName       string `json:"nick_name"`        // 昵称
	Avatar         string `json:"avatar"`           // 头像
	Password       string `json:"password"`         // 密码
	Email          string `json:"email"`            // 邮箱
	Mobile         string `json:"mobile"`           // 手机号
	Status         int64  `json:"status"`           // 状态  0：禁用   1：正常
	DeptId         int64  `json:"dept_id"`          // 部门ID
	CreateBy       string `json:"create_by"`        // 创建人
	CreateTime     int64  `json:"create_time"`      // 创建时间
	LastUpdateBy   string `json:"last_update_by"`   // 更新人
	LastUpdateTime int64  `json:"last_update_time"` // 更新时间
	DelFlag        int64  `json:"del_flag"`         // 是否删除  -1：已删除  0：正常
	RoleId         int64  `json:"role_id"`          // 岗位Id
	Sex            int64  `json:"sex"`              // 0男,1女
	Age            int64  `json:"age"`              // 默认0
	DeptName       string `json:"deptName"`
	RoleName       string `json:"roleName"`
}

type ListUserResp struct {
	Page     int64          `json:"page,default=1"`
	Data     []ListUserData `json:"data"`
	PageSize int64          `json:"pageSize,default=20"`
	Total    int64          `json:"total"`
}

type UpdateUserReq struct {
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	RoleId   int64  `json:"roleId"`
	Status   int64  `json:"status"`
}

type UpdateUserResp struct {
	Message string `json:"message"`
}

type EditUserReq struct {
	UserName string `json:"userName"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	RoleId   int64  `json:"roleId"`
	Status   int64  `json:"status"`
}

type EditUserResp struct {
	Message string `json:"message"`
}

type DeleteUserReq struct {
	UserName string `json:"userName"`
}

type DeleteUserResp struct {
	Message string `json:"message"`
}

type ReSetPasswordReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type ReSetPasswordResp struct {
	Message string `json:"message"`
}

type AddDeptReq struct {
	Name string `json:"name"` // 机构名称
}

type AddDeptResp struct {
	Message string `json:"message"`
}

type ListDeptReq struct {
}

type ListDeptData struct {
	Id             int64  `json:"id"`             // 编号
	Name           string `json:"name"`           // 机构名称
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64  `json:"delFlag"`        // 是否删除  -1：已删除  0：正常
}

type ListDeptResp struct {
	Message string         `json:"message"`
	Data    []ListDeptData `json:"data"`
	Total   int64          `json:"total"`
}

type UpdateDeptReq struct {
	Id   int64  `json:"id"`   // 编号
	Name string `json:"name"` // 机构名称
}

type UpdateDeptResp struct {
	Message string `json:"message"`
}

type DeleteDeptReq struct {
	Id int64 `json:"id"`
}

type DeleteDeptResp struct {
	Message string `json:"message"`
}

type AddRoleReq struct {
	Name string `json:"name"`
}

type AddRoleResp struct {
	Message string `json:"message"`
}

type ListRoleReq struct {
}

type ListRoleData struct {
	Id             int64  `json:"id"` // 编号
	Name           string `json:"name"`
	RoleType       int64  `json:"roleType"`       // 机构名称
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64  `json:"delFlag"`        // 是否删除  -1：已删除  0：正常
}

type ListRoleResp struct {
	Message string         `json:"message"`
	Data    []ListRoleData `json:"data"`
	Total   int64          `json:"total"`
}

type UpdateRoleReq struct {
	Id   int64  `json:"id"`   // 编号
	Name string `json:"name"` // 角色名称
}

type UpdateRoleResp struct {
	Message string `json:"message"`
}

type DeleteRoleReq struct {
	Id int64 `json:"id"`
}

type DeleteRoleResp struct {
	Message string `json:"message"`
}
