// Code generated by goctl. DO NOT EDIT!

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	oamUserRoleDeptFieldNames          = builder.RawFieldNames(&OamUserRoleDept{})
	oamUserRoleDeptRows                = strings.Join(oamUserRoleDeptFieldNames, ",")
	oamUserRoleDeptRowsExpectAutoSet   = strings.Join(stringx.Remove(oamUserRoleDeptFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	oamUserRoleDeptRowsWithPlaceHolder = strings.Join(stringx.Remove(oamUserRoleDeptFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	oamUserRoleDeptModel interface {
		Insert(ctx context.Context, data *OamUserRoleDept) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OamUserRoleDept, error)
		Update(ctx context.Context, newData *OamUserRoleDept) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOamUserRoleDeptModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OamUserRoleDept struct {
		Id             int64  `db:"id"`               // 编号
		RoleId         int64  `db:"role_id"`          // 角色ID
		DeptId         int64  `db:"dept_id"`          // 部门ID
		CreateBy       string `db:"create_by"`        // 创建人
		CreateTime     int64  `db:"create_time"`      // 创建时间
		LastUpdateBy   string `db:"last_update_by"`   // 更新人
		LastUpdateTime int64  `db:"last_update_time"` // 更新时间
	}
)

func newOamUserRoleDeptModel(conn sqlx.SqlConn) *defaultOamUserRoleDeptModel {
	return &defaultOamUserRoleDeptModel{
		conn:  conn,
		table: "`oam_user_role_dept`",
	}
}

func (m *defaultOamUserRoleDeptModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOamUserRoleDeptModel) FindOne(ctx context.Context, id int64) (*OamUserRoleDept, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", oamUserRoleDeptRows, m.table)
	var resp OamUserRoleDept
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOamUserRoleDeptModel) Insert(ctx context.Context, data *OamUserRoleDept) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, oamUserRoleDeptRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.DeptId, data.CreateBy, data.LastUpdateBy, data.LastUpdateTime)
	return ret, err
}

func (m *defaultOamUserRoleDeptModel) Update(ctx context.Context, data *OamUserRoleDept) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, oamUserRoleDeptRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.DeptId, data.CreateBy, data.LastUpdateBy, data.LastUpdateTime, data.Id)
	return err
}

func (m *defaultOamUserRoleDeptModel) tableName() string {
	return m.table
}
