// Code generated by goctl. DO NOT EDIT!

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	oamUserDeptFieldNames          = builder.RawFieldNames(&OamUserDept{})
	oamUserDeptRows                = strings.Join(oamUserDeptFieldNames, ",")
	oamUserDeptRowsExpectAutoSet   = strings.Join(stringx.Remove(oamUserDeptFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	oamUserDeptRowsWithPlaceHolder = strings.Join(stringx.Remove(oamUserDeptFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	oamUserDeptModel interface {
		Insert(ctx context.Context, data *OamUserDept) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OamUserDept, error)
		Update(ctx context.Context, newData *OamUserDept) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOamUserDeptModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OamUserDept struct {
		Id             int64  `db:"id"`               // 编号
		Name           string `db:"name"`             // 部门名称
		CreateBy       string `db:"create_by"`        // 创建人
		CreateTime     int64  `db:"create_time"`      // 创建时间
		LastUpdateBy   string `db:"last_update_by"`   // 更新人
		LastUpdateTime int64  `db:"last_update_time"` // 更新时间
		DelFlag        int64  `db:"del_flag"`         // 是否删除  -1：已删除  0：正常
	}
)

func newOamUserDeptModel(conn sqlx.SqlConn) *defaultOamUserDeptModel {
	return &defaultOamUserDeptModel{
		conn:  conn,
		table: "`oam_user_dept`",
	}
}

func (m *defaultOamUserDeptModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOamUserDeptModel) FindOne(ctx context.Context, id int64) (*OamUserDept, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", oamUserDeptRows, m.table)
	var resp OamUserDept
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOamUserDeptModel) Insert(ctx context.Context, data *OamUserDept) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, oamUserDeptRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.CreateBy, data.LastUpdateBy, data.LastUpdateTime, data.DelFlag)
	return ret, err
}

func (m *defaultOamUserDeptModel) Update(ctx context.Context, data *OamUserDept) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, oamUserDeptRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.CreateBy, data.LastUpdateBy, data.LastUpdateTime, data.DelFlag, data.Id)
	return err
}

func (m *defaultOamUserDeptModel) tableName() string {
	return m.table
}
